export {default as Rings} from './Rings'
export {default as Gate} from './Gate'
export {default as Map} from './Map'
export {default as PartnerPhotos} from './PartnerPhotos'
export {default as Gallery} from './Gallery'
export {default as Sounds} from './Sounds'